// Bus Call: account-free staff workflow using Firebase anonymous sessions + one shared room code.
(() => {
  const q=s=>document.querySelector(s);
  const panel=q('#busCallPanel');
  if(!panel)return;
  const connection=q('#busCallConnection'),setup=q('#busCallSetup'),callerConsole=q('#busCallerConsole'),teacherConsole=q('#busClassroomConsole'),errorEl=q('#busCallError');
  const popup=q('#busCallPopup'),popupNumber=q('#busPopupNumber'),popupNote=q('#busPopupNote'),popupTime=q('#busPopupTime');
  let role='',code='',room=null,unsubscribe=null,presenceDisconnect=null,lastCallId='',audioContext=null;
  const ROOM_MS=18*60*60*1000;
  const normalizeCode=value=>String(value||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8);
  const randomCode=()=>Array.from({length:5},()=>CODE_CHARS[Math.floor(Math.random()*CODE_CHARS.length)]).join('');
  const roomRef=value=>fb.ref(db,`busCallRooms/${value}`);
  const listenerRef=(value,uid)=>fb.ref(db,`busCallRooms/${value}/listeners/${uid}`);
  const setConnection=(text,state='')=>{connection.textContent=text;connection.classList.toggle('online',state==='online');connection.classList.toggle('problem',state==='problem')};
  const setError=text=>{errorEl.textContent=text||''};
  const cleanText=(value,max)=>String(value||'').trim().replace(/\s+/g,' ').slice(0,max);
  const formatTime=value=>{const date=new Date(Number(value)||Date.now());return date.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})};
  function saveTeacherPrefs(){try{localStorage.setItem('glnBusCallCode',code||normalizeCode(q('#busTeacherCodeInput').value));localStorage.setItem('glnBusCallTeacherName',q('#busTeacherNameInput').value.trim());localStorage.setItem('glnBusCallSound',q('#busSoundEnabled').checked?'1':'0')}catch{}}
  function restorePrefs(){try{q('#busTeacherCodeInput').value=normalizeCode(localStorage.getItem('glnBusCallCode')||'');q('#busTeacherNameInput').value=localStorage.getItem('glnBusCallTeacherName')||'';q('#busSoundEnabled').checked=localStorage.getItem('glnBusCallSound')!=='0'}catch{}}
  function stopWatch(){if(unsubscribe){unsubscribe();unsubscribe=null}}
  async function stopPresence(remove=true){if(presenceDisconnect){try{await presenceDisconnect.cancel()}catch{}presenceDisconnect=null}if(remove&&role==='teacher'&&code&&currentUser&&fb){try{await fb.remove(listenerRef(code,currentUser.uid))}catch{}}}
  function resetUi(){setup.hidden=false;callerConsole.hidden=true;teacherConsole.hidden=true;popup.hidden=true;role='';code='';room=null;lastCallId='';setConnection('Not connected');setError('')}
  function renderHistory(history={}){const list=q('#busCallHistory');const items=Object.values(history||{}).filter(Boolean).sort((a,b)=>(b.calledAt||0)-(a.calledAt||0)).slice(0,20);list.innerHTML='';if(!items.length){const p=document.createElement('p');p.textContent='No buses called yet.';list.append(p);return}items.forEach(item=>{const row=document.createElement('div');row.className='bus-history-row';const bus=document.createElement('b');bus.textContent=item.number||'—';const note=document.createElement('span');note.textContent=item.note||'Bus called';const time=document.createElement('time');time.textContent=formatTime(item.calledAt);row.append(bus,note,time);list.append(row)})}
  function renderCaller(value){const listeners=Object.values(value.listeners||{}).filter(item=>item?.connected!==false);q('#busListenerCount').textContent=`${listeners.length} classroom${listeners.length===1?'':'s'} online`;renderHistory(value.history);if(value.currentCall){q('#busCallerStatus').textContent=`Bus ${value.currentCall.number} was called at ${formatTime(value.currentCall.calledAt)}.`}else q('#busCallerStatus').textContent='Ready to call a bus.'}
  function beep(){if(!q('#busSoundEnabled').checked)return;try{audioContext=audioContext||new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const now=audioContext.currentTime;[0,.18].forEach((delay,index)=>{const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='sine';osc.frequency.value=index?880:660;gain.gain.setValueAtTime(.0001,now+delay);gain.gain.exponentialRampToValueAtTime(.18,now+delay+.015);gain.gain.exponentialRampToValueAtTime(.0001,now+delay+.16);osc.connect(gain).connect(audioContext.destination);osc.start(now+delay);osc.stop(now+delay+.18)})}catch{}}
  function showPopup(call,{test=false}={}){if(!call)return;popupNumber.textContent=cleanText(call.number,18)||'123';const note=cleanText(call.note,80);popupNote.textContent=note;popupNote.hidden=!note;popupTime.textContent=test?'Test alert':`Called at ${formatTime(call.calledAt)}`;popup.hidden=false;if(!test)beep()}
  function renderTeacher(value){q('#busTeacherConnectionText').textContent='Connected';const call=value.currentCall;if(!call){popup.hidden=true;q('#busWaitingTitle').textContent='Waiting for the next bus';q('#busWaitingDetail').textContent='A large alert will appear on this screen when the caller sends a bus number.';return}if(String(call.id)!==lastCallId){lastCallId=String(call.id);showPopup(call);q('#busWaitingTitle').textContent=`Last call: Bus ${call.number}`;q('#busWaitingDetail').textContent=`Called at ${formatTime(call.calledAt)}${call.note?` • ${call.note}`:''}`}}
  function watchRoom(){stopWatch();unsubscribe=fb.onValue(roomRef(code),snap=>{if(!snap.exists()){setError('This Bus Call room was closed or no longer exists.');setConnection('Room closed','problem');stopPresence(false);stopWatch();popup.hidden=true;return}room=snap.val()||{};if(room.expiresAt&&room.expiresAt<Date.now()){setError('This Bus Call room has expired. Start or join a new room.');setConnection('Room expired','problem');return}setConnection(role==='caller'?'Caller online':'Listening','online');if(role==='caller')renderCaller(room);else renderTeacher(room)},err=>{setConnection('Connection problem','problem');setError(err?.message||'Could not stay connected to the Bus Call room.')})}
  async function ensureFirebase(){setConnection('Connecting…');await initRaceFirebase();setConnection('Connected','online')}
  async function createCallerRoom(){setError('');try{await ensureFirebase();let requested=normalizeCode(q('#busCallerCodeInput').value),selected=requested||randomCode();let snap=await fb.get(roomRef(selected));if(snap.exists()){const existing=snap.val(),expired=!!(existing.expiresAt&&existing.expiresAt<Date.now());if(expired){await fb.set(roomRef(selected),{hostUid:currentUser.uid,status:'open',createdAt:Date.now(),expiresAt:Date.now()+ROOM_MS,currentCall:null,history:{},listeners:{}})}else{if(existing.hostUid!==currentUser.uid)throw new Error('That room code is already in use. Choose a different code.');if(!confirm(`Room ${selected} is already active. Reopen it?`))return}}else{await fb.set(roomRef(selected),{hostUid:currentUser.uid,status:'open',createdAt:Date.now(),expiresAt:Date.now()+ROOM_MS,currentCall:null,history:{},listeners:{}})}role='caller';code=selected;setup.hidden=true;callerConsole.hidden=false;teacherConsole.hidden=true;q('#busCallerRoomCode').textContent=code;q('#busCallerCodeInput').value=code;watchRoom();setTimeout(()=>q('#busNumberInput').focus(),0)}catch(error){setConnection('Could not connect','problem');setError(error.message||'Could not start Bus Call.')}}
  async function joinTeacherRoom(){setError('');const requested=normalizeCode(q('#busTeacherCodeInput').value),name=cleanText(q('#busTeacherNameInput').value,32)||'Classroom';try{if(requested.length<4)throw new Error('Enter the shared Bus Call room code.');await ensureFirebase();const snap=await fb.get(roomRef(requested));if(!snap.exists())throw new Error('Bus Call room not found. Check the room code.');const value=snap.val();if(value.status==='closed'||(value.expiresAt&&value.expiresAt<Date.now()))throw new Error('This Bus Call room is no longer active.');role='teacher';code=requested;lastCallId='';setup.hidden=true;callerConsole.hidden=true;teacherConsole.hidden=false;q('#busTeacherRoomCode').textContent=code;q('#busTeacherCodeInput').value=code;saveTeacherPrefs();const ref=listenerRef(code,currentUser.uid);await fb.set(ref,{id:currentUser.uid,name,connected:true,joinedAt:Date.now(),lastSeen:Date.now()});presenceDisconnect=fb.onDisconnect(ref);await presenceDisconnect.remove();watchRoom()}catch(error){setConnection('Could not join','problem');setError(error.message||'Could not join Bus Call.')}}
  async function sendCall(){if(role!=='caller'||!code)return;const number=cleanText(q('#busNumberInput').value,18),note=cleanText(q('#busCallNoteInput').value,80);if(!number){setError('Enter a bus number first.');q('#busNumberInput').focus();return}setError('');const button=q('#sendBusCall');button.disabled=true;try{const id=`${Date.now()}-${Math.random().toString(36).slice(2,7)}`,call={id,number,note,calledAt:fb.serverTimestamp()};const historyKey=fb.push(fb.ref(db,`busCallRooms/${code}/history`)).key;await fb.update(roomRef(code),{currentCall:call,[`history/${historyKey}`]:call,lastActivityAt:fb.serverTimestamp()});q('#busNumberInput').value='';q('#busCallNoteInput').value='';q('#busNumberInput').focus()}catch(error){setError(error.message||'Could not send the bus call.')}finally{button.disabled=false}}
  async function clearCurrent(){if(role!=='caller'||!code)return;try{await fb.update(roomRef(code),{currentCall:null,lastActivityAt:fb.serverTimestamp()});q('#busCallerStatus').textContent='Current call cleared.'}catch(error){setError(error.message||'Could not clear the current bus call.')}}
  async function clearHistory(){if(role!=='caller'||!code||!confirm('Clear the recent Bus Call history for this room?'))return;try{await fb.update(roomRef(code),{history:null})}catch(error){setError(error.message||'Could not clear Bus Call history.')}}
  async function closeRoom(){if(role!=='caller'||!code||!confirm(`Close Bus Call room ${code} for all classrooms?`))return;try{stopWatch();await fb.remove(roomRef(code));resetUi()}catch(error){setError(error.message||'Could not close the Bus Call room.')}}
  async function leaveRoom(){stopWatch();await stopPresence(true);resetUi();restorePrefs()}
  q('#startBusCaller').addEventListener('click',createCallerRoom);q('#joinBusRoom').addEventListener('click',joinTeacherRoom);q('#sendBusCall').addEventListener('click',sendCall);q('#busNumberInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();sendCall()}});q('#clearBusCall').addEventListener('click',clearCurrent);q('#clearBusHistory').addEventListener('click',clearHistory);q('#closeBusRoom').addEventListener('click',closeRoom);q('#leaveBusRoom').addEventListener('click',leaveRoom);q('#copyBusRoomCode').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(code);showToast('Bus Call room code copied')}catch{showToast(`Room code: ${code}`)}});q('#dismissBusPopup').addEventListener('click',()=>popup.hidden=true);q('#dismissBusPopupMain').addEventListener('click',()=>popup.hidden=true);q('#testBusAlert').addEventListener('click',()=>{try{audioContext=audioContext||new (window.AudioContext||window.webkitAudioContext)()}catch{}beep();showPopup({number:'123',note:'This is a test alert.',calledAt:Date.now()},{test:true})});q('#busSoundEnabled').addEventListener('change',saveTeacherPrefs);
  ['#busCallerCodeInput','#busTeacherCodeInput'].forEach(sel=>q(sel).addEventListener('input',e=>{const pos=e.target.selectionStart;e.target.value=normalizeCode(e.target.value);try{e.target.setSelectionRange(pos,pos)}catch{}}));
  window.addEventListener('beforeunload',()=>{if(role==='teacher'&&code&&currentUser&&fb){try{fb.update(listenerRef(code,currentUser.uid),{connected:false,lastSeen:Date.now()})}catch{}}});
  window.openBusCall=()=>setCalculatorMode('bus-call');
  window.refreshBusCall=()=>{if(role&&code)watchRoom()};
  restorePrefs();
})();
