const raceStage=document.querySelector('#raceStage'),raceJoin=document.querySelector('#raceJoin'),raceLobby=document.querySelector('#raceLobby'),raceLive=document.querySelector('#raceLive');
let raceCode='',raceHostToken='',racePlayerId='',racePlayerToken='',racePlayerName='',racePassageText='',raceTyped='',racePollTimer=null,raceSendTimer=null,raceStartedAt=0,raceCorrect=0,raceErrors=0,raceMode='';
const carColors=['🚗','🚙','🏎️','🚕','🚓','🚘'];
function openRace(){stopGame();gameGrid.hidden=true;gameStage.hidden=true;raceStage.hidden=false;raceJoin.hidden=false;raceLobby.hidden=true;raceLive.hidden=true;document.querySelector('#raceError').textContent='';document.querySelector('#raceCodeInput').value='';document.querySelector('#raceNameInput').value=''}
function closeRace(){clearInterval(racePollTimer);racePollTimer=null;clearTimeout(raceSendTimer);raceStage.hidden=true;raceCode='';raceHostToken='';racePlayerId='';racePlayerToken='';raceTyped='';raceMode=''}
document.querySelector('#backRace').onclick=()=>{closeRace();gameGrid.hidden=false};
async function raceApi(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'The race could not connect.');return data}
function raceError(message){document.querySelector('#raceError').textContent=message}
document.querySelector('#createRaceForm').onsubmit=async e=>{e.preventDefault();raceError('');try{const data=await raceApi('/api/race/create',{method:'POST',body:'{}'});raceCode=data.code;raceHostToken=data.hostToken;raceMode='host';showRaceLobby(data);beginRacePolling()}catch(error){raceError(error.message)}};
document.querySelector('#joinRaceForm').onsubmit=async e=>{e.preventDefault();raceError('');const code=document.querySelector('#raceCodeInput').value.trim().toUpperCase(),name=document.querySelector('#raceNameInput').value.trim();try{const data=await raceApi('/api/race/join',{method:'POST',body:JSON.stringify({code,name})});raceCode=code;racePlayerId=data.playerId;racePlayerToken=data.playerToken;racePlayerName=name;raceMode='player';showRaceLobby(data);beginRacePolling()}catch(error){raceError(error.message)}};
function showRaceLobby(data){raceJoin.hidden=true;raceLobby.hidden=false;raceLive.hidden=true;document.querySelector('#roomCode').textContent=raceCode;document.querySelector('#startRace').hidden=raceMode!=='host';document.querySelector('#lobbyTitle').textContent=raceMode==='host'?'Waiting for racers':'You are in!';document.querySelector('#lobbyHint').textContent=raceMode==='host'?'Share the room code. Start when everyone has joined.':'Waiting for the teacher to start the race.';renderLobbyPlayers(data.players||[])}
function renderLobbyPlayers(players){const box=document.querySelector('#lobbyPlayers');box.innerHTML='';if(!players.length){const empty=document.createElement('span');empty.textContent='No students yet';box.appendChild(empty);return}players.forEach(player=>{const chip=document.createElement('span');chip.textContent=`✓ ${player.name}`;box.appendChild(chip)})}
document.querySelector('#copyRaceCode').onclick=async()=>{try{await navigator.clipboard.writeText(raceCode);showToast('Room code copied')}catch{showToast(`Room code: ${raceCode}`)}};
document.querySelector('#startRace').onclick=async()=>{try{await raceApi('/api/race/start',{method:'POST',body:JSON.stringify({code:raceCode,hostToken:raceHostToken})})}catch(error){document.querySelector('#lobbyHint').textContent=error.message}};
function beginRacePolling(){clearInterval(racePollTimer);pollRace();racePollTimer=setInterval(pollRace,850)}
async function pollRace(){if(!raceCode)return;try{const query=new URLSearchParams({playerId:racePlayerId,playerToken:racePlayerToken});const data=await raceApi(`/api/race/${encodeURIComponent(raceCode)}?${query}`);document.querySelector('#raceConnection').textContent='Online';if(data.status==='waiting'){renderLobbyPlayers(data.players||[]);return}if(raceLive.hidden)beginLiveRace(data);renderRace(data)}catch(error){document.querySelector('#raceConnection').textContent='Reconnecting…'}}
function beginLiveRace(data){raceLobby.hidden=true;raceLive.hidden=false;racePassageText=data.passage;raceTyped='';raceStartedAt=Date.now();raceCorrect=0;raceErrors=0;renderRacePassage();renderRaceKeyboard();if(raceMode==='host')document.querySelector('#racePrompt').textContent='Teacher view — watch the racers move live.'}
function renderRace(data){const players=[...(data.players||[])].sort((a,b)=>b.progress-a.progress||a.finishedAt-b.finishedAt);const track=document.querySelector('#raceTrack');track.innerHTML='';players.forEach((player,index)=>{const lane=document.createElement('div');lane.className='race-lane';const name=document.createElement('span');name.className='race-lane-name';name.textContent=`${index+1}. ${player.name}`;const car=document.createElement('span');car.className='race-car';car.textContent=carColors[player.color%carColors.length];car.style.left=`${Math.min(91,player.progress*.91)}%`;const finish=document.createElement('span');finish.className='race-finish';lane.append(name,car,finish);track.appendChild(lane)});if(racePlayerId){const me=players.find(p=>p.id===racePlayerId),place=players.findIndex(p=>p.id===racePlayerId)+1;document.querySelector('#racePosition').textContent=me?.progress>=100?`Finished · #${place}`:`#${place} · ${Math.round(me?.progress||0)}%`}else document.querySelector('#racePosition').textContent=`${players.length} racer${players.length===1?'':'s'}`;if(data.status==='finished'){document.querySelector('#raceStatusText').textContent='Race finished!';document.querySelector('#racePrompt').textContent=players[0]?`Winner: ${players[0].name}`:'Race finished';clearInterval(racePollTimer)}}
function raceExpected(){if(racePassageText[raceTyped.length]===' ')return{key:'Space',value:' ',shift:false};return allMappings().find(item=>racePassageText.startsWith(item.value,raceTyped.length))||null}
function renderRacePassage(){const box=document.querySelector('#racePassage');box.innerHTML='';const done=document.createElement('span');done.className='done';done.textContent=racePassageText.slice(0,raceTyped.length);const current=document.createElement('span');current.className='current';current.textContent=racePassageText.slice(raceTyped.length,raceTyped.length+1);const rest=document.createTextNode(racePassageText.slice(raceTyped.length+1));box.append(done,current,rest)}
function renderRaceKeyboard(){const box=document.querySelector('#raceKeyboard');box.innerHTML='';const expected=raceExpected(),shifted=expected?.shift||false;rows.slice(1).forEach(row=>{const line=document.createElement('div');line.className='key-row';row.forEach(([key,normal,shift])=>{const button=document.createElement('button');button.type='button';button.className='key';button.innerHTML=`<small>${key}</small>${shifted?shift:normal}`;if(expected&&expected.key===key)button.classList.add('expected');button.onclick=()=>acceptRaceInput(shifted?shift:normal);line.appendChild(button)});box.appendChild(line)});const line=document.createElement('div'),space=document.createElement('button');line.className='key-row';space.type='button';space.className='key wide space';space.textContent='Space';if(expected?.key==='Space')space.classList.add('expected');space.onclick=()=>acceptRaceInput(' ');line.appendChild(space);box.appendChild(line)}
function acceptRaceInput(value){if(raceMode!=='player'||raceLive.hidden||raceTyped.length>=racePassageText.length)return;const remaining=racePassageText.slice(raceTyped.length);if(remaining.startsWith(value)){raceTyped+=value;raceCorrect+=value.length;document.querySelector('#racePrompt').textContent='Keep going!';renderRacePassage();renderRaceKeyboard();scheduleRaceProgress()}else{raceErrors++;const prompt=document.querySelector('#racePrompt');prompt.textContent='Try the highlighted key.';prompt.style.color='#c92525';setTimeout(()=>prompt.style.color='',220)}}
function scheduleRaceProgress(){clearTimeout(raceSendTimer);raceSendTimer=setTimeout(sendRaceProgress,120)}
async function sendRaceProgress(){const elapsed=Math.max(1,(Date.now()-raceStartedAt)/60000),progress=Math.min(100,raceTyped.length/racePassageText.length*100),wpm=Math.round((raceCorrect/5)/elapsed),accuracy=Math.round(raceCorrect/Math.max(1,raceCorrect+raceErrors)*100);try{await raceApi('/api/race/progress',{method:'POST',body:JSON.stringify({code:raceCode,playerId:racePlayerId,playerToken:racePlayerToken,progress,wpm,accuracy,finished:progress>=100})})}catch{}if(progress>=100)document.querySelector('#racePrompt').textContent=`Finished! ${wpm} WPM · ${accuracy}% accuracy`}
document.addEventListener('keydown',e=>{if(raceStage.hidden||raceLive.hidden||raceMode!=='player'||e.ctrlKey||e.metaKey||e.altKey||e.key==='Shift')return;let value;if(e.code==='Space')value=' ';else{const key=physicalKey(e),mapping=rows.flat().find(([mapped])=>mapped===key);if(!mapping)return;value=e.shiftKey?mapping[2]:mapping[1]}e.preventDefault();acceptRaceInput(value)});
